"""M22 — Index hoá schema (FK / status / timestamp) cho hiệu năng đọc dài hạn.

PRODUCTION_READINESS_REVIEW.html §Data: "Zero explicit indexes anywhere in the
schema beyond primary/unique keys" — Postgres không tự index cột FK, nên mọi
filter/join theo department_id, status, các cột *_at, và FK sang bảng khác đều
sequential scan khi bảng lớn dần. Thêm index có mục tiêu (không index cột chỉ
dùng để hiển thị tên qua object đã load — created_by/updated_by/verified_by/...
— vì grep xác nhận các cột đó không xuất hiện trong bất kỳ WHERE/JOIN nào), cộng
composite (department_id, status) cho các bảng nghiệp vụ chính, và composite
(owner_type, owner_id) cho bảng attachments (polymorphic, không có FK cứng
nhưng MỌI query list/download đều lọc theo cặp cột này).

Toàn bộ là CREATE INDEX thường (không CONCURRENTLY) — chạy trong transaction
của alembic, an toàn để rollback nếu lỗi giữa chừng; chấp nhận khoá bảng ngắn
lúc tạo vì dữ liệu hiện tại còn nhỏ (theo đúng ghi chú trade-off của review).
"""
from typing import Sequence, Union

from alembic import op

revision: str = "1718870400021"
down_revision: Union[str, None] = "1718870400020"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_index("ix_access_stats_user_id", "access_stats", ["user_id"])
    op.create_index("ix_attachments_uploaded_at", "attachments", ["uploaded_at"])
    op.create_index("ix_attachments_deleted_at", "attachments", ["deleted_at"])
    op.create_index("ix_audit_logs_user_id", "audit_logs", ["user_id"])
    op.create_index("ix_calibration_records_equipment_id", "calibration_records", ["equipment_id"])
    op.create_index("ix_calibration_records_correction_of", "calibration_records", ["correction_of"])
    op.create_index("ix_calibration_records_calibrated_at", "calibration_records", ["calibrated_at"])
    op.create_index("ix_calibration_records_created_at", "calibration_records", ["created_at"])
    op.create_index("ix_capa_nc_id", "capa", ["nc_id"])
    op.create_index("ix_capa_owner_id", "capa", ["owner_id"])
    op.create_index("ix_capa_status", "capa", ["status"])
    op.create_index("ix_capa_verified_at", "capa", ["verified_at"])
    op.create_index("ix_capa_closed_at", "capa", ["closed_at"])
    op.create_index("ix_capa_created_at", "capa", ["created_at"])
    op.create_index("ix_capa_actions_capa_id", "capa_actions", ["capa_id"])
    op.create_index("ix_capa_actions_assignee_id", "capa_actions", ["assignee_id"])
    op.create_index("ix_capa_actions_status", "capa_actions", ["status"])
    op.create_index("ix_capa_actions_done_at", "capa_actions", ["done_at"])
    op.create_index("ix_capa_actions_created_at", "capa_actions", ["created_at"])
    op.create_index("ix_capa_notification_dedup_capa_id", "capa_notification_dedup", ["capa_id"])
    op.create_index("ix_capa_notification_dedup_created_at", "capa_notification_dedup", ["created_at"])
    op.create_index("ix_chemical_lots_chemical_id", "chemical_lots", ["chemical_id"])
    op.create_index("ix_chemical_lots_price_unit", "chemical_lots", ["price_unit"])
    op.create_index("ix_chemical_lots_received_at", "chemical_lots", ["received_at"])
    op.create_index("ix_chemical_lots_created_at", "chemical_lots", ["created_at"])
    op.create_index("ix_chemical_lots_updated_at", "chemical_lots", ["updated_at"])
    op.create_index("ix_chemical_notification_dedup_lot_id", "chemical_notification_dedup", ["lot_id"])
    op.create_index("ix_chemical_notification_dedup_created_at", "chemical_notification_dedup", ["created_at"])
    op.create_index("ix_chemical_recheck_records_lot_id", "chemical_recheck_records", ["lot_id"])
    op.create_index("ix_chemical_recheck_records_attachment_id", "chemical_recheck_records", ["attachment_id"])
    op.create_index("ix_chemical_recheck_records_checked_at", "chemical_recheck_records", ["checked_at"])
    op.create_index("ix_chemical_recheck_records_created_at", "chemical_recheck_records", ["created_at"])
    op.create_index("ix_chemical_transactions_lot_id", "chemical_transactions", ["lot_id"])
    op.create_index("ix_chemical_transactions_base_unit", "chemical_transactions", ["base_unit"])
    op.create_index("ix_chemical_transactions_input_unit", "chemical_transactions", ["input_unit"])
    op.create_index("ix_chemical_transactions_price_unit", "chemical_transactions", ["price_unit"])
    op.create_index("ix_chemical_transactions_ref_sample_id", "chemical_transactions", ["ref_sample_id"])
    op.create_index("ix_chemical_transactions_by_user", "chemical_transactions", ["by_user"])
    op.create_index("ix_chemicals_base_unit", "chemicals", ["base_unit"])
    op.create_index("ix_chemicals_measurement_group", "chemicals", ["measurement_group"])
    op.create_index("ix_chemicals_department_id", "chemicals", ["department_id"])
    op.create_index("ix_chemicals_status", "chemicals", ["status"])
    op.create_index("ix_chemicals_created_at", "chemicals", ["created_at"])
    op.create_index("ix_chemicals_updated_at", "chemicals", ["updated_at"])
    op.create_index("ix_chemicals_department_id_status", "chemicals", ["department_id", "status"])
    op.create_index("ix_community_services_performer_user_id", "community_services", ["performer_user_id"])
    op.create_index("ix_community_services_department_id", "community_services", ["department_id"])
    op.create_index("ix_community_services_performed_at", "community_services", ["performed_at"])
    op.create_index("ix_community_services_created_at", "community_services", ["created_at"])
    op.create_index("ix_community_services_updated_at", "community_services", ["updated_at"])
    op.create_index("ix_competences_user_id", "competences", ["user_id"])
    op.create_index("ix_competences_created_at", "competences", ["created_at"])
    op.create_index("ix_competences_updated_at", "competences", ["updated_at"])
    op.create_index("ix_customers_deleted_at", "customers", ["deleted_at"])
    op.create_index("ix_customers_created_at", "customers", ["created_at"])
    op.create_index("ix_customers_updated_at", "customers", ["updated_at"])
    op.create_index("ix_departments_parent_id", "departments", ["parent_id"])
    op.create_index("ix_departments_status", "departments", ["status"])
    op.create_index("ix_document_access_log_document_id", "document_access_log", ["document_id"])
    op.create_index("ix_document_access_log_version_id", "document_access_log", ["version_id"])
    op.create_index("ix_document_access_log_user_id", "document_access_log", ["user_id"])
    op.create_index("ix_document_versions_document_id", "document_versions", ["document_id"])
    op.create_index("ix_document_versions_status", "document_versions", ["status"])
    op.create_index("ix_document_versions_created_at", "document_versions", ["created_at"])
    op.create_index("ix_document_versions_updated_at", "document_versions", ["updated_at"])
    op.create_index("ix_document_versions_submitted_at", "document_versions", ["submitted_at"])
    op.create_index("ix_document_versions_reviewed_at", "document_versions", ["reviewed_at"])
    op.create_index("ix_document_versions_approved_at", "document_versions", ["approved_at"])
    op.create_index("ix_document_versions_deleted_at", "document_versions", ["deleted_at"])
    op.create_index("ix_documents_type", "documents", ["type"])
    op.create_index("ix_documents_department_id", "documents", ["department_id"])
    op.create_index("ix_documents_status", "documents", ["status"])
    op.create_index("ix_documents_deleted_at", "documents", ["deleted_at"])
    op.create_index("ix_documents_created_at", "documents", ["created_at"])
    op.create_index("ix_documents_updated_at", "documents", ["updated_at"])
    op.create_index("ix_documents_department_id_status", "documents", ["department_id", "status"])
    op.create_index("ix_equipment_notification_dedup_equipment_id", "equipment_notification_dedup", ["equipment_id"])
    op.create_index("ix_equipment_notification_dedup_created_at", "equipment_notification_dedup", ["created_at"])
    op.create_index("ix_equipments_department_id", "equipments", ["department_id"])
    op.create_index("ix_equipments_responsible_user_id", "equipments", ["responsible_user_id"])
    op.create_index("ix_equipments_status", "equipments", ["status"])
    op.create_index("ix_equipments_created_at", "equipments", ["created_at"])
    op.create_index("ix_equipments_updated_at", "equipments", ["updated_at"])
    op.create_index("ix_equipments_deleted_at", "equipments", ["deleted_at"])
    op.create_index("ix_equipments_department_id_status", "equipments", ["department_id", "status"])
    op.create_index("ix_form_submissions_template_id", "form_submissions", ["template_id"])
    op.create_index("ix_form_submissions_department_id", "form_submissions", ["department_id"])
    op.create_index("ix_form_submissions_status", "form_submissions", ["status"])
    op.create_index("ix_form_submissions_submitted_at", "form_submissions", ["submitted_at"])
    op.create_index("ix_form_submissions_reviewed_at", "form_submissions", ["reviewed_at"])
    op.create_index("ix_form_submissions_department_id_status", "form_submissions", ["department_id", "status"])
    op.create_index("ix_form_templates_created_at", "form_templates", ["created_at"])
    op.create_index("ix_form_templates_updated_at", "form_templates", ["updated_at"])
    op.create_index("ix_hr_notification_dedup_profile_user_id", "hr_notification_dedup", ["profile_user_id"])
    op.create_index("ix_hr_notification_dedup_created_at", "hr_notification_dedup", ["created_at"])
    op.create_index("ix_hr_profiles_contract_type", "hr_profiles", ["contract_type"])
    op.create_index("ix_hr_profiles_created_at", "hr_profiles", ["created_at"])
    op.create_index("ix_hr_profiles_updated_at", "hr_profiles", ["updated_at"])
    op.create_index("ix_improvements_owner_id", "improvements", ["owner_id"])
    op.create_index("ix_improvements_department_id", "improvements", ["department_id"])
    op.create_index("ix_improvements_linked_nc_id", "improvements", ["linked_nc_id"])
    op.create_index("ix_improvements_status", "improvements", ["status"])
    op.create_index("ix_improvements_created_at", "improvements", ["created_at"])
    op.create_index("ix_improvements_updated_at", "improvements", ["updated_at"])
    op.create_index("ix_improvements_department_id_status", "improvements", ["department_id", "status"])
    op.create_index("ix_lab_access_cards_created_at", "lab_access_cards", ["created_at"])
    op.create_index("ix_lab_access_cards_updated_at", "lab_access_cards", ["updated_at"])
    op.create_index("ix_lab_registrations_mentor_id", "lab_registrations", ["mentor_id"])
    op.create_index("ix_lab_registrations_department_id", "lab_registrations", ["department_id"])
    op.create_index("ix_lab_registrations_status", "lab_registrations", ["status"])
    op.create_index("ix_lab_registrations_registered_at", "lab_registrations", ["registered_at"])
    op.create_index("ix_lab_registrations_approved_at", "lab_registrations", ["approved_at"])
    op.create_index("ix_lab_registrations_created_at", "lab_registrations", ["created_at"])
    op.create_index("ix_lab_registrations_updated_at", "lab_registrations", ["updated_at"])
    op.create_index("ix_lab_registrations_department_id_status", "lab_registrations", ["department_id", "status"])
    op.create_index("ix_nonconformities_department_id", "nonconformities", ["department_id"])
    op.create_index("ix_nonconformities_raised_by", "nonconformities", ["raised_by"])
    op.create_index("ix_nonconformities_status", "nonconformities", ["status"])
    op.create_index("ix_nonconformities_raised_at", "nonconformities", ["raised_at"])
    op.create_index("ix_nonconformities_created_at", "nonconformities", ["created_at"])
    op.create_index("ix_nonconformities_updated_at", "nonconformities", ["updated_at"])
    op.create_index("ix_nonconformities_department_id_status", "nonconformities", ["department_id", "status"])
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"])
    op.create_index("ix_notifications_read_at", "notifications", ["read_at"])
    op.create_index("ix_notifications_created_at", "notifications", ["created_at"])
    op.create_index("ix_overdue_reasons_sample_id", "overdue_reasons", ["sample_id"])
    op.create_index("ix_overdue_reasons_by_user", "overdue_reasons", ["by_user"])
    op.create_index("ix_project_members_created_at", "project_members", ["created_at"])
    op.create_index("ix_publication_authors_user_id", "publication_authors", ["user_id"])
    op.create_index("ix_publication_authors_created_at", "publication_authors", ["created_at"])
    op.create_index("ix_publications_category", "publications", ["category"])
    op.create_index("ix_publications_department_id", "publications", ["department_id"])
    op.create_index("ix_publications_created_at", "publications", ["created_at"])
    op.create_index("ix_publications_updated_at", "publications", ["updated_at"])
    op.create_index("ix_push_subscriptions_user_id", "push_subscriptions", ["user_id"])
    op.create_index("ix_push_subscriptions_created_at", "push_subscriptions", ["created_at"])
    op.create_index("ix_push_subscriptions_last_seen_at", "push_subscriptions", ["last_seen_at"])
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"])
    op.create_index("ix_refresh_tokens_rotated_from", "refresh_tokens", ["rotated_from"])
    op.create_index("ix_refresh_tokens_expires_at", "refresh_tokens", ["expires_at"])
    op.create_index("ix_refresh_tokens_revoked_at", "refresh_tokens", ["revoked_at"])
    op.create_index("ix_refresh_tokens_created_at", "refresh_tokens", ["created_at"])
    op.create_index("ix_research_projects_level", "research_projects", ["level"])
    op.create_index("ix_research_projects_lead_user_id", "research_projects", ["lead_user_id"])
    op.create_index("ix_research_projects_department_id", "research_projects", ["department_id"])
    op.create_index("ix_research_projects_status", "research_projects", ["status"])
    op.create_index("ix_research_projects_created_at", "research_projects", ["created_at"])
    op.create_index("ix_research_projects_updated_at", "research_projects", ["updated_at"])
    op.create_index("ix_research_projects_department_id_status", "research_projects", ["department_id", "status"])
    op.create_index("ix_risk_notification_dedup_risk_id", "risk_notification_dedup", ["risk_id"])
    op.create_index("ix_risk_notification_dedup_created_at", "risk_notification_dedup", ["created_at"])
    op.create_index("ix_risk_treatments_risk_id", "risk_treatments", ["risk_id"])
    op.create_index("ix_risk_treatments_owner_id", "risk_treatments", ["owner_id"])
    op.create_index("ix_risk_treatments_status", "risk_treatments", ["status"])
    op.create_index("ix_risk_treatments_done_at", "risk_treatments", ["done_at"])
    op.create_index("ix_risk_treatments_created_at", "risk_treatments", ["created_at"])
    op.create_index("ix_risks_owner_id", "risks", ["owner_id"])
    op.create_index("ix_risks_department_id", "risks", ["department_id"])
    op.create_index("ix_risks_status", "risks", ["status"])
    op.create_index("ix_risks_closed_at", "risks", ["closed_at"])
    op.create_index("ix_risks_created_at", "risks", ["created_at"])
    op.create_index("ix_risks_updated_at", "risks", ["updated_at"])
    op.create_index("ix_risks_department_id_status", "risks", ["department_id", "status"])
    op.create_index("ix_roles_permissions_resource", "roles_permissions", ["resource"])
    op.create_index("ix_roles_permissions_action", "roles_permissions", ["action"])
    op.create_index("ix_salary_history_user_id", "salary_history", ["user_id"])
    op.create_index("ix_salary_history_by_user", "salary_history", ["by_user"])
    op.create_index("ix_salary_history_created_at", "salary_history", ["created_at"])
    op.create_index("ix_sample_assignments_sample_id", "sample_assignments", ["sample_id"])
    op.create_index("ix_sample_assignments_assigned_to", "sample_assignments", ["assigned_to"])
    op.create_index("ix_sample_assignments_assigned_by", "sample_assignments", ["assigned_by"])
    op.create_index("ix_sample_assignments_status", "sample_assignments", ["status"])
    op.create_index("ix_sample_assignments_assigned_at", "sample_assignments", ["assigned_at"])
    op.create_index("ix_sample_assignments_created_at", "sample_assignments", ["created_at"])
    op.create_index("ix_sample_assignments_updated_at", "sample_assignments", ["updated_at"])
    op.create_index("ix_sample_dispatches_intake_id", "sample_dispatches", ["intake_id"])
    op.create_index("ix_sample_dispatches_target_department_id", "sample_dispatches", ["target_department_id"])
    op.create_index("ix_sample_dispatches_dispatched_by", "sample_dispatches", ["dispatched_by"])
    op.create_index("ix_sample_dispatches_status", "sample_dispatches", ["status"])
    op.create_index("ix_sample_dispatches_dispatched_at", "sample_dispatches", ["dispatched_at"])
    op.create_index("ix_sample_dispatches_received_at", "sample_dispatches", ["received_at"])
    op.create_index("ix_sample_dispatches_completed_at", "sample_dispatches", ["completed_at"])
    op.create_index("ix_sample_dispatches_updated_at", "sample_dispatches", ["updated_at"])
    op.create_index("ix_sample_handovers_sample_id", "sample_handovers", ["sample_id"])
    op.create_index("ix_sample_handovers_from_user", "sample_handovers", ["from_user"])
    op.create_index("ix_sample_handovers_to_user", "sample_handovers", ["to_user"])
    op.create_index("ix_sample_intakes_department_id", "sample_intakes", ["department_id"])
    op.create_index("ix_sample_intakes_received_by", "sample_intakes", ["received_by"])
    op.create_index("ix_sample_intakes_status", "sample_intakes", ["status"])
    op.create_index("ix_sample_intakes_received_at", "sample_intakes", ["received_at"])
    op.create_index("ix_sample_intakes_created_at", "sample_intakes", ["created_at"])
    op.create_index("ix_sample_intakes_updated_at", "sample_intakes", ["updated_at"])
    op.create_index("ix_sample_intakes_department_id_status", "sample_intakes", ["department_id", "status"])
    op.create_index("ix_sample_results_assignment_id", "sample_results", ["assignment_id"])
    op.create_index("ix_sample_results_entered_at", "sample_results", ["entered_at"])
    op.create_index("ix_sample_results_approved_at", "sample_results", ["approved_at"])
    op.create_index("ix_sample_results_created_at", "sample_results", ["created_at"])
    op.create_index("ix_samples_request_id", "samples", ["request_id"])
    op.create_index("ix_samples_department_id", "samples", ["department_id"])
    op.create_index("ix_samples_received_by", "samples", ["received_by"])
    op.create_index("ix_samples_current_custodian_id", "samples", ["current_custodian_id"])
    op.create_index("ix_samples_status", "samples", ["status"])
    op.create_index("ix_samples_condition_status", "samples", ["condition_status"])
    op.create_index("ix_samples_received_at", "samples", ["received_at"])
    op.create_index("ix_samples_deadline_at", "samples", ["deadline_at"])
    op.create_index("ix_samples_completed_at", "samples", ["completed_at"])
    op.create_index("ix_samples_deleted_at", "samples", ["deleted_at"])
    op.create_index("ix_samples_created_at", "samples", ["created_at"])
    op.create_index("ix_samples_updated_at", "samples", ["updated_at"])
    op.create_index("ix_samples_department_id_status", "samples", ["department_id", "status"])
    op.create_index("ix_samples_department_id_condition_status", "samples", ["department_id", "condition_status"])
    op.create_index("ix_student_mentorships_mentor_id", "student_mentorships", ["mentor_id"])
    op.create_index("ix_student_mentorships_type", "student_mentorships", ["type"])
    op.create_index("ix_student_mentorships_department_id", "student_mentorships", ["department_id"])
    op.create_index("ix_student_mentorships_created_at", "student_mentorships", ["created_at"])
    op.create_index("ix_student_mentorships_updated_at", "student_mentorships", ["updated_at"])
    op.create_index("ix_teaching_courses_user_id", "teaching_courses", ["user_id"])
    op.create_index("ix_teaching_courses_department_id", "teaching_courses", ["department_id"])
    op.create_index("ix_teaching_courses_created_at", "teaching_courses", ["created_at"])
    op.create_index("ix_teaching_courses_updated_at", "teaching_courses", ["updated_at"])
    op.create_index("ix_test_requests_customer_id", "test_requests", ["customer_id"])
    op.create_index("ix_test_requests_department_id", "test_requests", ["department_id"])
    op.create_index("ix_test_requests_received_by", "test_requests", ["received_by"])
    op.create_index("ix_test_requests_received_at", "test_requests", ["received_at"])
    op.create_index("ix_test_requests_deleted_at", "test_requests", ["deleted_at"])
    op.create_index("ix_test_requests_created_at", "test_requests", ["created_at"])
    op.create_index("ix_test_requests_updated_at", "test_requests", ["updated_at"])
    op.create_index("ix_users_department_id", "users", ["department_id"])
    op.create_index("ix_users_status", "users", ["status"])
    op.create_index("ix_users_last_login_at", "users", ["last_login_at"])
    op.create_index("ix_users_password_changed_at", "users", ["password_changed_at"])
    op.create_index("ix_users_created_at", "users", ["created_at"])
    op.create_index("ix_users_updated_at", "users", ["updated_at"])
    op.create_index("ix_users_department_id_status", "users", ["department_id", "status"])
    op.create_index("ix_attachments_owner_type_owner_id", "attachments", ["owner_type", "owner_id"])


def downgrade() -> None:
    op.drop_index("ix_attachments_owner_type_owner_id", table_name="attachments")
    op.drop_index("ix_users_department_id_status", table_name="users")
    op.drop_index("ix_users_updated_at", table_name="users")
    op.drop_index("ix_users_created_at", table_name="users")
    op.drop_index("ix_users_password_changed_at", table_name="users")
    op.drop_index("ix_users_last_login_at", table_name="users")
    op.drop_index("ix_users_status", table_name="users")
    op.drop_index("ix_users_department_id", table_name="users")
    op.drop_index("ix_test_requests_updated_at", table_name="test_requests")
    op.drop_index("ix_test_requests_created_at", table_name="test_requests")
    op.drop_index("ix_test_requests_deleted_at", table_name="test_requests")
    op.drop_index("ix_test_requests_received_at", table_name="test_requests")
    op.drop_index("ix_test_requests_received_by", table_name="test_requests")
    op.drop_index("ix_test_requests_department_id", table_name="test_requests")
    op.drop_index("ix_test_requests_customer_id", table_name="test_requests")
    op.drop_index("ix_teaching_courses_updated_at", table_name="teaching_courses")
    op.drop_index("ix_teaching_courses_created_at", table_name="teaching_courses")
    op.drop_index("ix_teaching_courses_department_id", table_name="teaching_courses")
    op.drop_index("ix_teaching_courses_user_id", table_name="teaching_courses")
    op.drop_index("ix_student_mentorships_updated_at", table_name="student_mentorships")
    op.drop_index("ix_student_mentorships_created_at", table_name="student_mentorships")
    op.drop_index("ix_student_mentorships_department_id", table_name="student_mentorships")
    op.drop_index("ix_student_mentorships_type", table_name="student_mentorships")
    op.drop_index("ix_student_mentorships_mentor_id", table_name="student_mentorships")
    op.drop_index("ix_samples_department_id_condition_status", table_name="samples")
    op.drop_index("ix_samples_department_id_status", table_name="samples")
    op.drop_index("ix_samples_updated_at", table_name="samples")
    op.drop_index("ix_samples_created_at", table_name="samples")
    op.drop_index("ix_samples_deleted_at", table_name="samples")
    op.drop_index("ix_samples_completed_at", table_name="samples")
    op.drop_index("ix_samples_deadline_at", table_name="samples")
    op.drop_index("ix_samples_received_at", table_name="samples")
    op.drop_index("ix_samples_condition_status", table_name="samples")
    op.drop_index("ix_samples_status", table_name="samples")
    op.drop_index("ix_samples_current_custodian_id", table_name="samples")
    op.drop_index("ix_samples_received_by", table_name="samples")
    op.drop_index("ix_samples_department_id", table_name="samples")
    op.drop_index("ix_samples_request_id", table_name="samples")
    op.drop_index("ix_sample_results_created_at", table_name="sample_results")
    op.drop_index("ix_sample_results_approved_at", table_name="sample_results")
    op.drop_index("ix_sample_results_entered_at", table_name="sample_results")
    op.drop_index("ix_sample_results_assignment_id", table_name="sample_results")
    op.drop_index("ix_sample_intakes_department_id_status", table_name="sample_intakes")
    op.drop_index("ix_sample_intakes_updated_at", table_name="sample_intakes")
    op.drop_index("ix_sample_intakes_created_at", table_name="sample_intakes")
    op.drop_index("ix_sample_intakes_received_at", table_name="sample_intakes")
    op.drop_index("ix_sample_intakes_status", table_name="sample_intakes")
    op.drop_index("ix_sample_intakes_received_by", table_name="sample_intakes")
    op.drop_index("ix_sample_intakes_department_id", table_name="sample_intakes")
    op.drop_index("ix_sample_handovers_to_user", table_name="sample_handovers")
    op.drop_index("ix_sample_handovers_from_user", table_name="sample_handovers")
    op.drop_index("ix_sample_handovers_sample_id", table_name="sample_handovers")
    op.drop_index("ix_sample_dispatches_updated_at", table_name="sample_dispatches")
    op.drop_index("ix_sample_dispatches_completed_at", table_name="sample_dispatches")
    op.drop_index("ix_sample_dispatches_received_at", table_name="sample_dispatches")
    op.drop_index("ix_sample_dispatches_dispatched_at", table_name="sample_dispatches")
    op.drop_index("ix_sample_dispatches_status", table_name="sample_dispatches")
    op.drop_index("ix_sample_dispatches_dispatched_by", table_name="sample_dispatches")
    op.drop_index("ix_sample_dispatches_target_department_id", table_name="sample_dispatches")
    op.drop_index("ix_sample_dispatches_intake_id", table_name="sample_dispatches")
    op.drop_index("ix_sample_assignments_updated_at", table_name="sample_assignments")
    op.drop_index("ix_sample_assignments_created_at", table_name="sample_assignments")
    op.drop_index("ix_sample_assignments_assigned_at", table_name="sample_assignments")
    op.drop_index("ix_sample_assignments_status", table_name="sample_assignments")
    op.drop_index("ix_sample_assignments_assigned_by", table_name="sample_assignments")
    op.drop_index("ix_sample_assignments_assigned_to", table_name="sample_assignments")
    op.drop_index("ix_sample_assignments_sample_id", table_name="sample_assignments")
    op.drop_index("ix_salary_history_created_at", table_name="salary_history")
    op.drop_index("ix_salary_history_by_user", table_name="salary_history")
    op.drop_index("ix_salary_history_user_id", table_name="salary_history")
    op.drop_index("ix_roles_permissions_action", table_name="roles_permissions")
    op.drop_index("ix_roles_permissions_resource", table_name="roles_permissions")
    op.drop_index("ix_risks_department_id_status", table_name="risks")
    op.drop_index("ix_risks_updated_at", table_name="risks")
    op.drop_index("ix_risks_created_at", table_name="risks")
    op.drop_index("ix_risks_closed_at", table_name="risks")
    op.drop_index("ix_risks_status", table_name="risks")
    op.drop_index("ix_risks_department_id", table_name="risks")
    op.drop_index("ix_risks_owner_id", table_name="risks")
    op.drop_index("ix_risk_treatments_created_at", table_name="risk_treatments")
    op.drop_index("ix_risk_treatments_done_at", table_name="risk_treatments")
    op.drop_index("ix_risk_treatments_status", table_name="risk_treatments")
    op.drop_index("ix_risk_treatments_owner_id", table_name="risk_treatments")
    op.drop_index("ix_risk_treatments_risk_id", table_name="risk_treatments")
    op.drop_index("ix_risk_notification_dedup_created_at", table_name="risk_notification_dedup")
    op.drop_index("ix_risk_notification_dedup_risk_id", table_name="risk_notification_dedup")
    op.drop_index("ix_research_projects_department_id_status", table_name="research_projects")
    op.drop_index("ix_research_projects_updated_at", table_name="research_projects")
    op.drop_index("ix_research_projects_created_at", table_name="research_projects")
    op.drop_index("ix_research_projects_status", table_name="research_projects")
    op.drop_index("ix_research_projects_department_id", table_name="research_projects")
    op.drop_index("ix_research_projects_lead_user_id", table_name="research_projects")
    op.drop_index("ix_research_projects_level", table_name="research_projects")
    op.drop_index("ix_refresh_tokens_created_at", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_revoked_at", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_expires_at", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_rotated_from", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_index("ix_push_subscriptions_last_seen_at", table_name="push_subscriptions")
    op.drop_index("ix_push_subscriptions_created_at", table_name="push_subscriptions")
    op.drop_index("ix_push_subscriptions_user_id", table_name="push_subscriptions")
    op.drop_index("ix_publications_updated_at", table_name="publications")
    op.drop_index("ix_publications_created_at", table_name="publications")
    op.drop_index("ix_publications_department_id", table_name="publications")
    op.drop_index("ix_publications_category", table_name="publications")
    op.drop_index("ix_publication_authors_created_at", table_name="publication_authors")
    op.drop_index("ix_publication_authors_user_id", table_name="publication_authors")
    op.drop_index("ix_project_members_created_at", table_name="project_members")
    op.drop_index("ix_overdue_reasons_by_user", table_name="overdue_reasons")
    op.drop_index("ix_overdue_reasons_sample_id", table_name="overdue_reasons")
    op.drop_index("ix_notifications_created_at", table_name="notifications")
    op.drop_index("ix_notifications_read_at", table_name="notifications")
    op.drop_index("ix_notifications_user_id", table_name="notifications")
    op.drop_index("ix_nonconformities_department_id_status", table_name="nonconformities")
    op.drop_index("ix_nonconformities_updated_at", table_name="nonconformities")
    op.drop_index("ix_nonconformities_created_at", table_name="nonconformities")
    op.drop_index("ix_nonconformities_raised_at", table_name="nonconformities")
    op.drop_index("ix_nonconformities_status", table_name="nonconformities")
    op.drop_index("ix_nonconformities_raised_by", table_name="nonconformities")
    op.drop_index("ix_nonconformities_department_id", table_name="nonconformities")
    op.drop_index("ix_lab_registrations_department_id_status", table_name="lab_registrations")
    op.drop_index("ix_lab_registrations_updated_at", table_name="lab_registrations")
    op.drop_index("ix_lab_registrations_created_at", table_name="lab_registrations")
    op.drop_index("ix_lab_registrations_approved_at", table_name="lab_registrations")
    op.drop_index("ix_lab_registrations_registered_at", table_name="lab_registrations")
    op.drop_index("ix_lab_registrations_status", table_name="lab_registrations")
    op.drop_index("ix_lab_registrations_department_id", table_name="lab_registrations")
    op.drop_index("ix_lab_registrations_mentor_id", table_name="lab_registrations")
    op.drop_index("ix_lab_access_cards_updated_at", table_name="lab_access_cards")
    op.drop_index("ix_lab_access_cards_created_at", table_name="lab_access_cards")
    op.drop_index("ix_improvements_department_id_status", table_name="improvements")
    op.drop_index("ix_improvements_updated_at", table_name="improvements")
    op.drop_index("ix_improvements_created_at", table_name="improvements")
    op.drop_index("ix_improvements_status", table_name="improvements")
    op.drop_index("ix_improvements_linked_nc_id", table_name="improvements")
    op.drop_index("ix_improvements_department_id", table_name="improvements")
    op.drop_index("ix_improvements_owner_id", table_name="improvements")
    op.drop_index("ix_hr_profiles_updated_at", table_name="hr_profiles")
    op.drop_index("ix_hr_profiles_created_at", table_name="hr_profiles")
    op.drop_index("ix_hr_profiles_contract_type", table_name="hr_profiles")
    op.drop_index("ix_hr_notification_dedup_created_at", table_name="hr_notification_dedup")
    op.drop_index("ix_hr_notification_dedup_profile_user_id", table_name="hr_notification_dedup")
    op.drop_index("ix_form_templates_updated_at", table_name="form_templates")
    op.drop_index("ix_form_templates_created_at", table_name="form_templates")
    op.drop_index("ix_form_submissions_department_id_status", table_name="form_submissions")
    op.drop_index("ix_form_submissions_reviewed_at", table_name="form_submissions")
    op.drop_index("ix_form_submissions_submitted_at", table_name="form_submissions")
    op.drop_index("ix_form_submissions_status", table_name="form_submissions")
    op.drop_index("ix_form_submissions_department_id", table_name="form_submissions")
    op.drop_index("ix_form_submissions_template_id", table_name="form_submissions")
    op.drop_index("ix_equipments_department_id_status", table_name="equipments")
    op.drop_index("ix_equipments_deleted_at", table_name="equipments")
    op.drop_index("ix_equipments_updated_at", table_name="equipments")
    op.drop_index("ix_equipments_created_at", table_name="equipments")
    op.drop_index("ix_equipments_status", table_name="equipments")
    op.drop_index("ix_equipments_responsible_user_id", table_name="equipments")
    op.drop_index("ix_equipments_department_id", table_name="equipments")
    op.drop_index("ix_equipment_notification_dedup_created_at", table_name="equipment_notification_dedup")
    op.drop_index("ix_equipment_notification_dedup_equipment_id", table_name="equipment_notification_dedup")
    op.drop_index("ix_documents_department_id_status", table_name="documents")
    op.drop_index("ix_documents_updated_at", table_name="documents")
    op.drop_index("ix_documents_created_at", table_name="documents")
    op.drop_index("ix_documents_deleted_at", table_name="documents")
    op.drop_index("ix_documents_status", table_name="documents")
    op.drop_index("ix_documents_department_id", table_name="documents")
    op.drop_index("ix_documents_type", table_name="documents")
    op.drop_index("ix_document_versions_deleted_at", table_name="document_versions")
    op.drop_index("ix_document_versions_approved_at", table_name="document_versions")
    op.drop_index("ix_document_versions_reviewed_at", table_name="document_versions")
    op.drop_index("ix_document_versions_submitted_at", table_name="document_versions")
    op.drop_index("ix_document_versions_updated_at", table_name="document_versions")
    op.drop_index("ix_document_versions_created_at", table_name="document_versions")
    op.drop_index("ix_document_versions_status", table_name="document_versions")
    op.drop_index("ix_document_versions_document_id", table_name="document_versions")
    op.drop_index("ix_document_access_log_user_id", table_name="document_access_log")
    op.drop_index("ix_document_access_log_version_id", table_name="document_access_log")
    op.drop_index("ix_document_access_log_document_id", table_name="document_access_log")
    op.drop_index("ix_departments_status", table_name="departments")
    op.drop_index("ix_departments_parent_id", table_name="departments")
    op.drop_index("ix_customers_updated_at", table_name="customers")
    op.drop_index("ix_customers_created_at", table_name="customers")
    op.drop_index("ix_customers_deleted_at", table_name="customers")
    op.drop_index("ix_competences_updated_at", table_name="competences")
    op.drop_index("ix_competences_created_at", table_name="competences")
    op.drop_index("ix_competences_user_id", table_name="competences")
    op.drop_index("ix_community_services_updated_at", table_name="community_services")
    op.drop_index("ix_community_services_created_at", table_name="community_services")
    op.drop_index("ix_community_services_performed_at", table_name="community_services")
    op.drop_index("ix_community_services_department_id", table_name="community_services")
    op.drop_index("ix_community_services_performer_user_id", table_name="community_services")
    op.drop_index("ix_chemicals_department_id_status", table_name="chemicals")
    op.drop_index("ix_chemicals_updated_at", table_name="chemicals")
    op.drop_index("ix_chemicals_created_at", table_name="chemicals")
    op.drop_index("ix_chemicals_status", table_name="chemicals")
    op.drop_index("ix_chemicals_department_id", table_name="chemicals")
    op.drop_index("ix_chemicals_measurement_group", table_name="chemicals")
    op.drop_index("ix_chemicals_base_unit", table_name="chemicals")
    op.drop_index("ix_chemical_transactions_by_user", table_name="chemical_transactions")
    op.drop_index("ix_chemical_transactions_ref_sample_id", table_name="chemical_transactions")
    op.drop_index("ix_chemical_transactions_price_unit", table_name="chemical_transactions")
    op.drop_index("ix_chemical_transactions_input_unit", table_name="chemical_transactions")
    op.drop_index("ix_chemical_transactions_base_unit", table_name="chemical_transactions")
    op.drop_index("ix_chemical_transactions_lot_id", table_name="chemical_transactions")
    op.drop_index("ix_chemical_recheck_records_created_at", table_name="chemical_recheck_records")
    op.drop_index("ix_chemical_recheck_records_checked_at", table_name="chemical_recheck_records")
    op.drop_index("ix_chemical_recheck_records_attachment_id", table_name="chemical_recheck_records")
    op.drop_index("ix_chemical_recheck_records_lot_id", table_name="chemical_recheck_records")
    op.drop_index("ix_chemical_notification_dedup_created_at", table_name="chemical_notification_dedup")
    op.drop_index("ix_chemical_notification_dedup_lot_id", table_name="chemical_notification_dedup")
    op.drop_index("ix_chemical_lots_updated_at", table_name="chemical_lots")
    op.drop_index("ix_chemical_lots_created_at", table_name="chemical_lots")
    op.drop_index("ix_chemical_lots_received_at", table_name="chemical_lots")
    op.drop_index("ix_chemical_lots_price_unit", table_name="chemical_lots")
    op.drop_index("ix_chemical_lots_chemical_id", table_name="chemical_lots")
    op.drop_index("ix_capa_notification_dedup_created_at", table_name="capa_notification_dedup")
    op.drop_index("ix_capa_notification_dedup_capa_id", table_name="capa_notification_dedup")
    op.drop_index("ix_capa_actions_created_at", table_name="capa_actions")
    op.drop_index("ix_capa_actions_done_at", table_name="capa_actions")
    op.drop_index("ix_capa_actions_status", table_name="capa_actions")
    op.drop_index("ix_capa_actions_assignee_id", table_name="capa_actions")
    op.drop_index("ix_capa_actions_capa_id", table_name="capa_actions")
    op.drop_index("ix_capa_created_at", table_name="capa")
    op.drop_index("ix_capa_closed_at", table_name="capa")
    op.drop_index("ix_capa_verified_at", table_name="capa")
    op.drop_index("ix_capa_status", table_name="capa")
    op.drop_index("ix_capa_owner_id", table_name="capa")
    op.drop_index("ix_capa_nc_id", table_name="capa")
    op.drop_index("ix_calibration_records_created_at", table_name="calibration_records")
    op.drop_index("ix_calibration_records_calibrated_at", table_name="calibration_records")
    op.drop_index("ix_calibration_records_correction_of", table_name="calibration_records")
    op.drop_index("ix_calibration_records_equipment_id", table_name="calibration_records")
    op.drop_index("ix_audit_logs_user_id", table_name="audit_logs")
    op.drop_index("ix_attachments_deleted_at", table_name="attachments")
    op.drop_index("ix_attachments_uploaded_at", table_name="attachments")
    op.drop_index("ix_access_stats_user_id", table_name="access_stats")
